apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: wwbdocker123/payments
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'https://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://payments-mongo-srv:27017/payments'
            - name: JWT_KEY # name of the new environment variable inside of the container auth
              valueFrom:
                secretKeyRef:
                  name: jwt-secret # mame of the secret object
                  key: JWT_KEY # key of the key/value pair
            - name: STRIPE_KEY # name of the new environment variable inside of the container auth
              valueFrom:
                secretKeyRef:
                  name: stripe-secret # mame of the secret object
                  key: STRIPE_KEY # key of the key/value pair
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srvc
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
