name: tests-payments

on:
  pull_request
    paths:
      - 'payments/**'

jobs:
  build:
    runs-on: ubuntu-latest # the container
    steps:
      - uses: actions/checkout@v2 # take all the codes of the project
      - run: cd payments && npm install && npm run test:ci
