name: tests-orders

on:
  pull_request
    paths:
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest # the container
    steps:
      - uses: actions/checkout@v2 # take all the codes of the project
      - run: cd orders && npm install && npm run test:ci
